version: "3.8"

services:
    nginx:
        container_name: ${APP_NAME:-numbernine}_nginx
        image: nginx:alpine
        ports:
            - ${NGINX_PORT:-443}:443
        environment:
            NGINX_PORT: ${NGINX_PORT:-443}
            SERVER_NAME: ${SERVER_NAME:-localhost}
            PHP_SERVICE: ${PHP_SERVICE:-php}
        restart: always
        working_dir: /srv/app
        volumes:
            - ./docker/nginx/templates:/etc/nginx/templates

    php:
        container_name: ${APP_NAME:-numbernine}_php
        image: numberninecms/php:7.4-fpm
        working_dir: /srv/app
        user: '1000'
        restart: always
        env_file:
            - .env.local
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379

    mysql:
        container_name: ${APP_NAME:-numbernine}_mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        container_name: ${APP_NAME:-numbernine}_redis
        image: redis:alpine
        restart: always
        ports:
            - ${REDIS_PORT:-6379}

volumes:
    mysql_data:
    app_files:
    app_var:
