version: "3.4"

# Development environment override
services:
    php:
        volumes:
            - ./:/srv/app:rw,cached
            - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
            # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
            # - ./api/var:/srv/app/var:rw
        environment:
            APP_ENV: dev

    phpmyadmin:
        container_name: numbernine_app_phpmyadmin
        image: phpmyadmin/phpmyadmin:fpm-alpine
        volumes:
            - phpmyadmin_data:/var/www/html/
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
            - PMA_ARBITRARY=1
        restart: unless-stopped
        depends_on:
            - mysql
        networks:
            - numbernine

    caddy:
        volumes:
            - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./public:/srv/app/public:ro
            - phpmyadmin_data:/var/www/html/:ro
        depends_on:
            - mysql
            - phpmyadmin

volumes:
    phpmyadmin_data:
