version: "3.8"

services:
    app:
        container_name: numbernine_demo_app_files
        image: repo/image:tag # Change this with your app image
        command: chown -R '1000:1000' .
        volumes:
            - app_files:/srv/app

    nginx:
        container_name: numbernine_demo_nginx
        image: nginx:alpine
        ports:
            - 10000:443
        restart: always
        working_dir: /srv/app
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - app_files:/srv/app
            - ./.env:/srv/app/.env
            - /etc/letsencrypt:/etc/letsencrypt

    php:
        container_name: numbernine_demo_php
        image: numberninecms/php:7.4-fpm
        user: '1000:1000'
        working_dir: /srv/app
        restart: always
        env_file:
            - .env.local
        volumes:
            - app_files:/srv/app
            - ./docker/php/symfony.ini:/etc/php7/conf.d/symfony.ini

    mysql:
        container_name: numbernine_demo_mysql
        image: mysql:8
        user: '1000:1000'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_USER: numbernine_demo_staging
            MYSQL_PASSWORD: tP6pC7zsJhQeOgNDzxkzJRul3vVVko6D7VGNAnLt1kOON0W2ig
            MYSQL_ROOT_PASSWORD: tvyNSB2uZlnQxRv14xFDW7bPz2JpTLobj0HN5a8JsT0kvm4ORI
            MYSQL_DATABASE: numbernine_demo_staging
        ports:
            - 5556:3306
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        container_name: numbernine_demo_redis
        image: redis:alpine
        user: '1000:1000'
        restart: always

volumes:
    mysql_data:
    app_files:

