version: "3.8"

services:
    nginx:
        volumes:
            - ./docker/nginx/cert/localhost.crt:/etc/ssl/certs/localhost.crt
            - ./docker/nginx/cert/localhost.key:/etc/ssl/private/localhost.key
            - ../:/srv/app/vendor/numberninecms
    php:
        volumes:
            - ../:/srv/app/vendor/numberninecms
    redis:
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
