version: "3.8"

services:
    nginx:
        volumes:
            - ./docker/nginx/cert/localhost.crt:/etc/ssl/certs/localhost.crt
            - ./docker/nginx/cert/localhost.key:/etc/ssl/private/localhost.key
            - ./:/srv/app

    php:
        image: numberninecms/php:7.4-fpm-dev
        env_file:
            - .env
        environment:
            BLACKFIRE_CLIENT_ID: ~
            BLACKFIRE_CLIENT_TOKEN: ~
        volumes:
            - ./:/srv/app
            - ./docker/php/xdebug.ini:/etc/php7/conf.d/xdebug.ini
            - ./docker/php/blackfire.ini:/etc/php7/conf.d/blackfire.ini
            - ../:/srv/app/vendor/numberninecms
        links:
            - blackfire

    mysql:
        environment:
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=numbernine_app

    redis:
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}

    blackfire:
        container_name: ${APP_NAME:-numbernine}_blackfire
        image: blackfire/blackfire
        restart: always
        ports:
            - "8707:8707"
        environment:
            BLACKFIRE_CLIENT_ID: ~
            BLACKFIRE_CLIENT_TOKEN: ~
            BLACKFIRE_SERVER_ID: ~
            BLACKFIRE_SERVER_TOKEN: ~

