name: Staging

on:
    workflow_run:
        workflows:
            - Test
        branches:
            - master
        types:
            - completed

jobs:
    build:
        name: Build and deploy

        if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}

        runs-on: ubuntu-20.04

        strategy:
            matrix:
                php: [ '8.1' ]

        steps:
            -   uses: FranzDiebold/github-env-vars-action@v2

            -   uses: actions/checkout@v2

            -   name: Setup PHP
                id: setup-php
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip
                    tools: composer:v2
                    coverage: none
                env:
                    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                run: |
                    echo "APP_ENV=prod" > .env
                    echo "LOCK_DSN=semaphore" >> .env
                    echo "APP_SECRET=$(openssl rand -base64 48)" >> .env
                    echo "APP_NAME=numbernine_demo" >> .env
                    echo "DATABASE_URL=mysql://user:user@mysql:3306/numbernine_demo?serverVersion=8.0" >> .env
                    echo "REDIS_URL=redis://redis:6379" >> .env
                    echo "MAILER_DSN=" >> .env
                    rm composer.lock
                    composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction
                    composer dump-autoload --classmap-authoritative --no-dev
                    composer run-script --no-dev post-install-cmd

            -   name: Build assets
                run: |
                    yarn install
                    yarn build

            -   name: Build Docker image
                run: |
                    docker build --no-cache -t ${{ secrets.DOCKER_REPO }}-php:latest -f ./docker/Dockerfile --target app_php .
                    docker build --no-cache -t ${{ secrets.DOCKER_REPO }}-nginx:latest -f ./docker/Dockerfile --target app_nginx .

            -   name: Push Docker image
                run: |
                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                    docker push --all-tags ${{ secrets.DOCKER_REPO }}-php
                    docker push --all-tags ${{ secrets.DOCKER_REPO }}-nginx

            -   name: Deploy
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    passphrase: ${{ secrets.SSH_PASSPHRASE }}
                    port: ${{ secrets.SSH_PORT }}
                    script: ${{ secrets.SSH_COMMAND }}
